Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/focal64"
	config.vm.provision :shell, path: "bootstrap.sh"
	config.vm.hostname = "imunes-box"
	config.vm.provider "virtualbox" do |virtualmachine|
		virtualmachine.gui = true
		virtualmachine.name = "IMUNES-Ubuntu-20.04"
		virtualmachine.memory = 4096
		virtualmachine.cpus = 2
	end
end
